lib/podlet.js

This adds error event listeners on the metric stream. Guards against errors in the stream.

Add error event listeners on all metric streams

---

lib/podlet.js
package.json

No point in using `merge` when the source object is an empty object.

refactor: remove pointless lodash method

---

lib/podlet.js
package.json

Follow ups https://github.com/podium-lib/issues/issues/9. Use the new JSON Schema to validate arguments.
**NOTE:** one test is failing due to the validation rule. Seems like the `uri` validator does accept empty values. Fixed in the schema: https://github.com/podium-lib/schemas/pull/6

Use new schema to validate arguments

---

README.md
__tests__/podlet.js
lib/podlet.js
package.json

This takes use of the new `js` and `css` properties at root in the new manifest schema. Its also made sure that the previous `assets.js` and `assets.css` properties is set as previously so version 3 layouts will be able to use the manifest from a version 4 podlet.
In other words; there will be a period when the manifest will contain duplicates to maintain backwards compabillity:
```json
{
"name": "podletContent",
"version": "2.0.0-1554932811522",
"content": "/",
"fallback": "/fallback",
"assets": {
"js": "/assets/module.js",
"css": "/assets/module.css"
},
"css": [
{ "value": "/assets/module.css", "type": "module" }
],
"js": [
{ "value": "/assets/module.js", "type": "module" }
],
"proxy": {}
}
```

Use the new .js and .css fields in the new schema

---

__tests__/podlet.js
lib/podlet.js

Somewhere between (oldest) https://github.com/podium-lib/podlet/blob/f3493b6031c731fa45b6cc971604531a7ec9f9ee/lib/podlet.js#L293-L333 and (newest) https://github.com/podium-lib/podlet/blob/14df5a87e59c0e4878d138bfa284edc5f56df2e4/lib/podlet.js#L293-L331 `return incoming` have dissapeard from the `.process()` method.
The weird thing here is that the dissapearense does not show up in any of the commits (oldest) https://github.com/podium-lib/podlet/commit/f3493b6031c731fa45b6cc971604531a7ec9f9ee / (newest) https://github.com/podium-lib/podlet/commit/14df5a87e59c0e4878d138bfa284edc5f56df2e4 
This reintroduces that `.process()` returns `HttpIncoming`.

Return HttpIncoming

---

lib/podlet.js

This fixes a bug where the html document used in development in a podlet would be served when a layout requests it. This would cause a double html document in the final rendered html from the layout server.
This would only happen when a Podlet is in development mode and requested from layout server.

Fix for dev mode sending document when UA is set

---

__tests__/podlet.js
lib/podlet.js

This removes the limitation of how many assets can be set. In v3.x this was limited to one asset (a bundle) but in v4 we opened for this being multiple. Until now we kept the limitation to one through the API for backwards compabillity but under further consideration it seems like we do not need to.
In other words; one can now do as follow:
```js
const podlet = new Podlet({ ... });
podlet.css({ value: 'a.css' });
podlet.css({ value: 'b.css' });
podlet.css({ value: 'c.css' });
```

Remove limitation of how many assets which can be set

---

README.md
__tests__/podlet.js
lib/podlet.js
package.json

This adds `type` as argument to the `.js()` method. It also sets the default value to `default`. This will normally be used to define which type of script we have and can be used to reflect this in `<script>` tags.
Example: `type` set to `module` will set `<script type="module">` in the default template making it possible to load ES6 modules directly.

Added type as argument to .js method

---

README.md
__tests__/podlet.js
lib/podlet.js

This adds a options argument to the `podlet.process()` method with a `proxy` property which can be `true` or `false`.
The reason behind adding this it that inside the `podlet.process()` method we set sertain properties on `HttpIncoming` pluss calling the `proxy.process()` method for doing proxying. This works fine when doing setup as in a Express middelware, but in some http frameworks we need to separate the process of setting properties on `HttpIncoming` and setting up the proxy by calling `proxy.process()`. 
The new option property `proxy` makes it possible to turn the setup of proxying inside `podlet.proxess()` on or off making it easier to implement support for different http frameworks.

Made proxying in the process method configurable

---

__tests__/podlet.js
package.json

Replaces the internal destination stream helper method with the one in @podium/test-utils.

Use @podium/test-utils for destination stream

---

__tests__/podlet.js
lib/podlet.js
package.json

This refactors the `.render()` method and how the document template is written. The main change here is that `HttpIncoming` is now passed on as the first argument to the document template and that the second argument is always a String intended to be the "body" of the document. 
We do also remove the `.render()` method on `HttpIncoming` and change the `.view` property to be a placeholder for properties intended to be used by the document template.
A document template does now have the following signature:
```js
const document = (incoming, data) => {
return `
<html>
<head><title>${incoming.view.title}</title></head>
<body>${data}</body>
</html>
`;
}
```
When rendering one will now do as follow:
```js
app.get('/', async (req, res, next) => {
const incoming = res.locals.podium;
incoming.view …
```

Refactor render method

---

__tests__/podlet.js
lib/podlet.js

The `publicPathname` value on the development context was always being set to the podlet's pathname when the proxy was mounting proxies at pathname + prefix + name.

use pathnameBuilder to set publicPathname

---

__tests__/podlet.compabillity.js
__tests__/podlet.js
lib/deprecations.js
lib/podlet.js

From V3 to V4 we deprecated the return value from the `.js()` and `.css()` methods. In V5 we will remove that these return a value.
Due to this an deprecation message was added but the deprecation message is printed when these methods are used. Calling these methods to set a value will trigger the deprecation message which are not quite what we want. 
This little hack makes it so that the deprecation message is printed only when one try to use the returned value from these methods.
This will **not** trigger a deprecation message:
```js
const css = podlet.css({ value: '/public/css/main.css' });
```
This will trigger a deprecation message:
```js
const css = podlet.css({ value: '/public/css/main.css' });
app.get(css, (req, res) => {
[ .... ]
});
```

Print deprecation message only on usage of the returned .js() and .css() value

---

__tests__/podlet.compabillity.js
__tests__/podlet.js
lib/podlet.js
package.json

This uses the new CSS and JS asset classes introduced in https://github.com/podium-lib/utils/pull/18
This makes it possible to set all the HTML attributes one would like on CSS and JS assets.
```js
const podlet = new Podlet({ ... });
podlet.js({
value: '/foo/script.js',
async: true,
type: 'esm',
});
podlet.css({
value: '/foo/light.css',
title: 'Normal mode',
});
podlet.css({
value: '/foo/dark.css',
title: 'Dark mode',
});
```

Use asset classes

---

lib/podlet.js

This makes sure that all arguments one set on the `.css()` and `.js()` methods is passed on to the new asset classes when instantiating new asset objects.
This is still a bit messy, but will be a lot cleaner when we can remove the backwards compatibility.

Pass all arguments on to the asset classes

---

index.d.ts
package.json

This pull request adds TypeScript declarations to this module.
Since we have first class support for Express I've added the `podiumSend` method to the express response type. This is achieved through [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html).
A minor issue is that the method doesn't exist unless the podlet's middleware has been hooked up in express, but we have no way of typing this (that I know of).

add typescript declarations

---

__tests__/podlet.compatibility.js
__tests__/podlet.js
lib/podlet.js

I discovered that it was not possible to pass an instance of `AssetJs` to `.js()` nor an instance of `AssetCss` to `.css()` due to `Object.assign` not calling the instances `.toJSON` method. The easiest solution was to just clone the object using `JSON.parse(JSON.stringify(options))`. How do you feel about this approach? @trygve-lie 
Also, sorry about the formatting and renaming noise

Fix asset js and css methods

---

__tests__/podlet.compatibility.js

Jest 25.1.0 [break tests](https://github.com/podium-lib/podlet/actions/runs/31635012) due to [a change](https://github.com/podium-lib/podlet/actions/runs/31635012) in their `.toStrictEqual()` which seems to bleed into `.toEqual()` making it behave slightly different than before.
Doing a simple fix due to this being tests on deprecated and to be removed code.

Prepare for jest breaking tests

---

lib/podlet.js

This make it so that we inherit the URL values from express and depend on those instead of parsing out these by our self.
The advantage of this is that we are then moving the responsibility of handling `x-forwarded` headers etc to Express and is not an extra thing in Podium. It improves security and makes the URL values in Express content and Podium identical.

Inherit URL values from Express

---

tests/podlet.js

Not 100% sure why some tests started to [fail on node 14](https://github.com/podium-lib/podlet/actions/runs/114686658) but my hunch is that its related to a fair bit of clean up in the streams event order in node 14. The reason for our tests starting to fail is probably a bug which has been masked / eaten by slightly uneven event order.
The error starting to occur on node 14 in one of our tests was:
```sh
stack: |
tests/podlet.js:796:27
Server.<anonymous> (tests/podlet.js:39:19)
at:
line: 643
column: 15
file: _http_outgoing.js
function: writeAfterEnd
code: ERR_STREAM_WRITE_AFTER_END
tapCaught: uncaughtException
test: ".process() - .process(HttpIncoming, { proxy: true }) - request to proxy
path - should do proxying"
```
The reason for the error is that in our test code, its written on the …

Fix tests for node 14

---

lib/podlet.js
tests/podlet.js

This adds support for setting data attributes through the `.js()` method like so:
```js
podlet.js([
{ 
value: '/assets/script.js',
data: {
bar: 'a',
foo: 'b'
} 
}
]);
```
This will then be represented in the html template like so:
```html
<script src="/assets/script.js" data-bar="a" data-foo="b"></script>
```
Originally suggested in https://github.com/podium-lib/utils/pull/58

feat: Added support for data-* attributes on .js() method

---

package.json

Update dependencies to add support for manifest files which can hold an Array of proxy endpoints instead of using object notation for proxy endpoints.
Ref: https://github.com/podium-lib/proxy/pull/226 and https://github.com/podium-lib/schemas/pull/161

fix: Use latest proxy

---

index.d.ts

This PR adds type information for the remaining properties on objects create from the Podlet class.

fix: adding type information closes #344

---

lib/podlet.js
tests/podlet.js

This PR adds development support for the new scope feature of asset objects.
Scope is handled in the Podium client in prod but in local development it needs to work as well so this PR adds asset filtering based on scope (content or fallback)
The defined content and fallback routes are matched against the request pathname to determine if a route is a content route of a fallback route. Once determined, it can then be compared against each asset object's scope property.

feat: filter assets by scope if scope is provided

---

lib/podlet.js
package.json
tests/podlet.js

The podlet was not passing res.locals to HttpIncoming which is something we do in the layout as well as both the Fastify layout and podlet. 
Fixing this will make it easier to handle locale and other request bound values in the document template as prior to this fix, we couldn't rely on params being set, eg. incoming.params.locale was not available in the podlet context.

Pass params to http incoming

---

tests/podlet.test.js

Just verifying that scopes work with early hints... which they do.

test: add tests for scope

---

package.json
tests/podlet.test.js

This brings in the @podium/utils asset-type link header attribute which makes it easier for serialisation/deserialisation of asset objects to and from a link header. The podlet writes an asset-type attribute and the Podium client can then use it to tell which type of asset objects to create from the header

fix: update @podium/utils

---

README.md
lib/podlet.js
package.json
tests/podlet.test.js

This PR is a second attempt (after feedback) for implementing DSD wrapping for podlets.
A new constructor argument has been added
```js
const podlet = new Podlet({
name: 'my-podlet', // when useShadowDOM is set to true, name must be valid custom element name
useShadowDOM: true,
});
```
and asset scopes can be used to place assets inside the Shadow DOM.
```js
podlet.css({ value: '/path/to/css', scope: 'shadow-dom' });
```
For the base use case, thats all you need to do.

DSD Shadow dom

---

lib/podlet.js

The default value mentioned in the JSDoc for the constructor and in the property were not accurate.

fix: correct the JSDoc for fallback

---

lib/podlet.js
package.json

With utils 5.2.1, headers are no longer tagged with asset-type so we do that here in the podlet instead

fix: tag asset type when sending hint headers

---

README.md
lib/podlet.js

re: Feedback from Dave H that it could be nice to include the invalid name in the message. I also saw that it was probably worth mentioning the use of the wrapWithShadowDOM method in case it is being used directly

fix: sharpen up shadow dom usage assertion

---

lib/podlet.js
tests/podlet.test.js

Early hints is a no go since some load balancers (eg. Google's load balancer in k8s) simply don't support early hints at all.
This PR does the next best thing which is to send the early hints as a Link header with all the other headers. It's slightly more awkward and by default there won't be a performance win at all but with a new method `res.sendHeaders` it becomes possible to send the headers first and the body afterwards. In both cases, assets will be sent request bound which is what we want.
If the user does nothing except upgrade to this version of the podlet, assets will be sent request bound but there won't be a performance win...
```js
app.get(podlet.content(), (req, res) => {
res.podiumSend('...');
});
```
The user can use the sendHeaders function to control when the headers are …

Replace early hints
